name = "agex-images-worker"
compatibility_date = "2025-11-18"

type = "javascript"

account_id = "REPLACE_WITH_YOUR_ACCOUNT_ID"
workers_dev = true
route = "images.agexparts.com/*"

[triggers]
# cron = "..."

[env.production]
workers_dev = false
route = "images.agexparts.com/*"
